[global]
listener_host = "127.0.0.1"
listener_port = 8080

[[proxy_pass]]
source_path = "/api"
target_path = "/"
target_port = 8000
target_host = "127.0.0.1"

[[proxy_pass]]
source_path = "/users"
target_path = "/users"
target_port = 9000
target_host = "127.0.0.1"
